# Generated by Django 5.1.4 on 2025-03-25 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_original_cart_order_stripe_pid'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceticket',
            name='associated_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='completion_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
