# Generated by Django 5.1.4 on 2025-03-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenanceticket_associated_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='maintenance_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
