# Generated by Django 5.1.4 on 2025-03-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenanceticket_maintenance_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('fixed', 'Fixed'), ('written_off', 'Written Off')], default='pending', max_length=12),
        ),
    ]
