# Generated by Django 5.1.4 on 2025-03-11 10:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='partyitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='partyitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='partyitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='partyitem',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='partyitem',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='partyitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='partyitem',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='partyitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='products.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
