# Generated by Django 5.1.4 on 2025-03-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_partyitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='sku',
            field=models.CharField(default='abc123', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='serial_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
