# Generated by Django 5.1.4 on 2025-03-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_tool_sku_alter_tool_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='sku',
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(default='abc123', max_length=255),
            preserve_default=False,
        ),
    ]
